config/routes.rb
Rails.application.routes.draw do
  
  root 'landings#new'
  get 'thankyou' => 'landings#thankyou'
  get 'index' => 'landings#index'

  resources :landings, only: [:index, :create]
end

app/models/landing.rb
class Landing < ActiveRecord::Base
	validates :name, presence: true, length: { maximum: 30 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, format: { with: VALID_EMAIL_REGEX }, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  before_action :set_landing, only: [:destroy]
  http_basic_authenticate_with name: "example", password: "pa$$w0rd", except: [:new, :create, :thankyou]

  def index
    @landings = Landing.all
  end

  def thankyou
  end

  def new
    @landing = Landing.new
  end

  def create
    @landing = Landing.new(landing_params)

    if @landing.save
      WelcomeMailer.welcome(@landing).deliver
      redirect_to thankyou_path, notice: 'Success!'
    else
      render action: 'new'
    end
  end

  def destroy
    @landing.destroy
    respond_to do |format|
      format.html { redirect_to landings_url, notice: 'Landing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_landing
      @landing = Landing.find(params[:id])
    end

    def landing_params
      params.require(:landing).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/views/landings/_form.html.erb
<%= form_for(@landing) do |f| %>
  <% if @landing.errors.any? %>
    <div id="error_explanation">
      <% @landing.errors.full_messages.each do |message| %>
        <error><%= message %></error>
      <% end %>
    </div>
  <% end %>

  <div class="input-group">
    <%= f.text_field :name, label: false, placeholder: "Name"%>
  </div>
  <div class="input-group">
    <%= f.text_field :email, label: false, placeholder: "Email"%>
  </div>
  <div>
    <%= f.submit "SUBMIT", class: "btn-custom" %>
  </div>
<% end %>

app/views/landings/edit.html.erb
<h1>Editing landing</h1>

<%= render 'form' %>

<%= link_to 'Show', @landing %> |
<%= link_to 'Back', landings_path %>

app/views/landings/index.html.erb
<div class="index overlay">
  <h2>Captured Emails</h2>
  <% @landings.each do |landing| %>
    <tr>
      <p><%= landing.email %> | <%= link_to 'Delete', landing, method: :delete, data: { confirm: 'Are you sure?' } %></p>
    </tr>
  <% end %>
<br>
  <%= link_to 'Home', root_path %>
</div>

app/views/landings/new.html.erb
<div class="center">
<img src="assets/logo.png" id="logo">
	<h4 class="header">We're building something awesome, sign-up to find out when it's available.</h4>
	<div class="main">
		<%= render 'form' %>
		<div class="social center">
			<a href="#"><i class="fa fa-facebook"></i></a>
			<a href="#"><i class="fa fa-twitter"></i></a>
			<a href="#"><i class="fa fa-instagram"></i></a>
		</div>
	</div>
</div>		

app/views/landings/thankyou.html.erb
<div class="center">
<img src="/assets/logo.png" id="logo">
	<h4 class="header">Thank you for your interest, we'll be sending you updates periodically on our progress.</h4>
	<div class="main">
		<%= link_to 'Back', root_path, class: "btn-custom" %>
		<br>
		<div class="social center">
			<a href="#"><i class="fa fa-facebook"></i></a>
			<a href="#"><i class="fa fa-twitter"></i></a>
			<a href="#"><i class="fa fa-instagram"></i></a>
		</div>
	</div>
</div>		

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Landing Page</title>
  <meta name="description" content="Demo - Fullscreen Landing Page" />
  <meta name="keywords" content="open, source, fullscreen, image, coming, soon, pre, launch, landing, page, construction, lead, generation, rails, collect, email, sign-up, collection, beta, code, free, demo, tutorial, github" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body id="background-image">

<%= yield %>
<footer><a href="https://github.com/mhill426/rails-landing-page" target="_blank">Open Source</a> by <a href="#" target="_blank">Oleg Pritula</a></footer>
</body>
</html>